name: Benchmarks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install CLR requirements
        run: |
          sudo apt-get -y update
          sudo apt-get install -y cmake llvm-9 clang-9 autoconf automake \
          libtool build-essential python curl git lldb-6.0 liblldb-6.0-dev \
          libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev \
          libssl-dev libnuma-dev libkrb5-dev zlib1g-dev
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101'

      - name: Build Python Package
        shell: bash
        run: python -m pip install --upgrade pip && pip install .

      - name: Run benchmark tests
        shell: bash
        run: |
          python -m pip install  django==3.1.4
          python Tests/benchmarks/test_nbody.py
          python Tests/benchmarks/test_nqueens.py
          python Tests/benchmarks/test_fannkuch.py
          python Tests/benchmarks/test_chaos.py
          python Tests/benchmarks/test_float.py
          python Tests/benchmarks/test_django_template.py

  build-macos-10:
    runs-on: macos-10.15
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101'

      - name: Build Python Package
        shell: bash
        run: python -m pip install --upgrade pip && pip install .

      - name: Run benchmark tests
        shell: bash
        run: |
          python -m pip install  django==3.1.4
          python Tests/benchmarks/test_nbody.py
          python Tests/benchmarks/test_nqueens.py
          python Tests/benchmarks/test_fannkuch.py
          python Tests/benchmarks/test_chaos.py
          python Tests/benchmarks/test_float.py
          python Tests/benchmarks/test_django_template.py


  build-macos-11:
    runs-on: macos-11.0
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101'

      - name: Build Python Package
        shell: bash
        run: python -m pip install --upgrade pip && pip install .

      - name: Run benchmark tests
        shell: bash
        run: |
          python -m pip install  django==3.1.4
          python Tests/benchmarks/test_nbody.py
          python Tests/benchmarks/test_nqueens.py
          python Tests/benchmarks/test_fannkuch.py
          python Tests/benchmarks/test_chaos.py
          python Tests/benchmarks/test_float.py
          python Tests/benchmarks/test_django_template.py

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config Release

      - name: Install build deps
        shell: bash
        run: python -m pip install -U https://github.com/tonybaloney/scikit-build/archive/vs2019.zip

      - name: Build Python Package
        shell: bash
        run: python setup.py build --generator "Visual Studio 16 2019"

      - name: Install Python Package
        shell: bash
        run: python setup.py install --generator "Visual Studio 16 2019"

      - name: Run benchmark tests
        shell: bash
        run: |
          python -m pip install  django==3.1.4
          python Tests/benchmarks/test_nbody.py
          python Tests/benchmarks/test_nqueens.py
          python Tests/benchmarks/test_fannkuch.py
          python Tests/benchmarks/test_chaos.py
          python Tests/benchmarks/test_float.py
          python Tests/benchmarks/test_django_template.py
